<a href="https://colab.research.google.com/github/liannekc/Pandas-Numpys-Python/blob/main/HW2_Chu_Lianne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
#Q1-1
import pandas as pd
df = pd.DataFrame(data)
print(df)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


In [ ]:
#Q1-2
df[((df["job"]=="psychologist")| (df["job"]=="teacher")) & (df["num_cars"] > df["family_size"])]

name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [ ]:
#Q1-3
df[(df["family_size"] < 3) & (df["num_cars"] > 0)]

name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

In [ ]:
#Q1-4
length = len(df.job.unique())
print("Number of unique jobs:", length)

Number of unique jobs: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))


In [ ]:
weights.groupby(fruit).mean()


apple     5.5
banana    3.0
carrot    6.0
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
print(course_name)

['Python' 'JS' 'examples' 'PHP' 'html']


In [ ]:
#Q3-1
#capitalize first letter so it can sort properly
capitalize = np.char.capitalize(course_name)
sorted_index_course = np.argsort(capitalize)
print(sorted_index_course) 


[2 4 1 3 0]


In [ ]:
#Q3-2
x = np.char.startswith(course_name,'P')
print(x)

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q4-1
print(student_id)
reversed = student_id[::-1]
print(reversed)


[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [ ]:
#Q4-2
#sorts is first by index
sorted_index_array = np.argsort(student_id) 

# sorted array with actual vaues
sorted_array = student_id[sorted_index_array] 
# 3 largest values
print(sorted_array[-3:])



[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
arr = np.arange(1, 100)

# find  multiples of 3 or 5 below 100
multiples= arr[(arr % 3 == 0) | (arr % 5 == 0)]

# print sum multiples
print(multiples.sum())

# Hint: you can use arange to start off

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Swap column 1 with column 2
arr[:,[1, 2]] = arr[:,[2, 1]]
print(arr)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [ ]:
# swap row 0 with row 1
arr[[0, 1],:] = arr[[1, 0],:]
print(arr)

[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
